namespace HardwareInfo.Types;

public enum Bios
{
    BiosCharacteristics,
    BIOSVersion,
    BuildNumber,
    Caption,
    CodeSet,
    CurrentLanguage,
    Description,
    EmbeddedControllerMajorVersion,
    EmbeddedControllerMinorVersion,
    IdentificationCode,
    InstallableLanguages,
    InstallDate,
    LanguageEdition,
    ListOfLanguages,
    Manufacturer,
    Name,
    OtherTargetOS,
    PrimaryBIOS,
    ReleaseDate,
    SerialNumber,
    SMBIOSBIOSVersion,
    SMBIOSMajorVersion,
    SMBIOSMinorVersion,
    SMBIOSPresent,
    SoftwareElementID,
    SoftwareElementState,
    Status,
    SystemBiosMajorVersion,
    SystemBiosMinorVersion,
    TargetOperatingSystem,
    Version
}