using HardwareInfo.Types;

namespace HardwareInfo.Extensions;

public static class OsExtensions
{
    public static string GetText(this Os value) => value switch
    {
        Os.BootDevice => "BootDevice",
        Os.BuildNumber => "BuildNumber",
        Os.BuildType => "BuildType",
        Os.Caption => "Caption",
        Os.CodeSet => "CodeSet",
        Os.CountryCode => "CountryCode",
        Os.CreationClassName => "CreationClassName",
        Os.CSCreationClassName => "CSCreationClassName",
        Os.CSDVersion => "CSDVersion",
        Os.CSName => "CSName",
        Os.CurrentTimeZone => "CurrentTimeZone",
        Os.DataExecutionPrevention_32BitApplications => "DataExecutionPrevention_32BitApplications",
        Os.DataExecutionPrevention_Available => "DataExecutionPrevention_Available",
        Os.DataExecutionPrevention_Drivers => "DataExecutionPrevention_Drivers",
        Os.DataExecutionPrevention_SupportPolicy => "DataExecutionPrevention_SupportPolicy",
        Os.Debug => "Debug",
        Os.Description => "Description",
        Os.Distributed => "Distributed",
        Os.EncryptionLevel => "EncryptionLevel",
        Os.ForegroundApplicationBoost => "ForegroundApplicationBoost",
        Os.FreePhysicalMemory => "FreePhysicalMemory",
        Os.FreeSpaceInPagingFiles => "FreeSpaceInPagingFiles",
        Os.FreeVirtualMemory => "FreeVirtualMemory",
        Os.InstallDate => "InstallDate",
        Os.LargeSystemCache => "LargeSystemCache",
        Os.LastBootUpTime => "LastBootUpTime",
        Os.LocalDateTime => "LocalDateTime",
        Os.Locale => "Locale",
        Os.Manufacturer => "Manufacturer",
        Os.MaxNumberOfProcesses => "MaxNumberOfProcesses",
        Os.MaxProcessMemorySize => "MaxProcessMemorySize",
        Os.MUILanguages => "MUILanguages",
        Os.Name => "Name",
        Os.NumberOfLicensedUsers => "NumberOfLicensedUsers",
        Os.NumberOfProcesses => "NumberOfProcesses",
        Os.NumberOfUsers => "NumberOfUsers",
        Os.OperatingSystemSKU => "OperatingSystemSKU",
        Os.Organization => "Organization",
        Os.OSArchitecture => "OSArchitecture",
        Os.OSLanguage => "OSLanguage",
        Os.OSProductSuite => "OSProductSuite",
        Os.OSType => "OSType",
        Os.OtherTypeDescription => "OtherTypeDescription",
        Os.PAEEnabled => "PAEEnabled",
        Os.PlusProductID => "PlusProductID",
        Os.PlusVersionNumber => "PlusVersionNumber",
        Os.PortableOperatingSystem => "PortableOperatingSystem",
        Os.Primary => "Primary",
        Os.ProductType => "ProductType",
        Os.RegisteredUser => "RegisteredUser",
        Os.SerialNumber => "SerialNumber",
        Os.ServicePackMajorVersion => "ServicePackMajorVersion",
        Os.ServicePackMinorVersion => "ServicePackMinorVersion",
        Os.SizeStoredInPagingFiles => "SizeStoredInPagingFiles",
        Os.Status => "Status",
        Os.SuiteMask => "SuiteMask",
        Os.SystemDevice => "SystemDevice",
        Os.SystemDirectory => "SystemDirectory",
        Os.SystemDrive => "SystemDrive",
        Os.TotalSwapSpaceSize => "TotalSwapSpaceSize",
        Os.TotalVirtualMemorySize => "TotalVirtualMemorySize",
        Os.TotalVisibleMemorySize => "TotalVisibleMemorySize",
        Os.Version => "Version",
        Os.WindowsDirectory => "WindowsDirectory",
        _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
    };
}